{{- $fullName := include "snowstorm.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-browser
  labels:
    app: browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      initContainers:
      - name: wait-for-snowstorm
        image: public.ecr.aws/docker/library/busybox:1.36
        command: ['sh', '-c', 'until wget -q -O- http://{{ $fullName }}-snowstorm:8080/actuator/health; do echo "Waiting for Snowstorm API"; sleep 5; done;']
      containers:
      - name: browser
        image: {{ .Values.browser.image.repository }}:{{ .Values.browser.image.tag }}
        imagePullPolicy: {{ .Values.browser.image.pullPolicy | default "IfNotPresent" }}
        env:
        - name: API_HOST
          value: http://{{ $fullName }}-snowstorm:8080/
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        resources:
          {{- toYaml .Values.browser.resources | nindent 10 }}
