{{- $fullName := include "snowstorm.fullname" . -}}

{{- if .Values.elasticsearch.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-elasticsearch
  labels:
    {{- include "snowstorm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elasticsearch.service.type }}
  selector:
    app: elasticsearch
  ports:
  - port: {{ .Values.elasticsearch.service.port | default 9200 }}
    targetPort: 9200
{{- end -}}
