{{- $fullName := include "snowstorm.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        env:
        - name: discovery.type
          value: {{ .Values.elasticsearch.environment.DISCOVERY_TYPE }}
        - name: xpack.security.enabled
          value: "{{ .Values.elasticsearch.environment.XPACK_SECURITY_ENABLED }}"
        - name: node.name
          value: {{ .Values.elasticsearch.environment.NODE_NAME }}
        - name: cluster.name
          value: {{ .Values.elasticsearch.environment.CLUSTER_NAME }}
        - name: ES_JAVA_OPTS
          value: {{ .Values.elasticsearch.environment.ES_JAVA_OPTS }}
        ports:
        - containerPort: 9200
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:9200
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
    {{- if .Values.elasticsearch.persistence.enabled -}}
        volumeMounts:
        - name: elasticsearch-storage
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elasticsearch-storage
        persistentVolumeClaim:
          claimName: {{ include "snowstorm.fullname" . }}-elasticsearch
    {{- end -}}