{{- $fullName := include "snowstorm.fullname" . -}}
{{- $selectorLabels := include "snowstorm.selectorLabels" . -}}

{{- if .Values.snowstorm.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-snowstorm
  labels:
    {{- include "snowstorm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.snowstorm.service.type }}
  selector:
    app: snowstorm
  ports:
  - port: {{ .Values.snowstorm.service.port | default 8080 }}
    targetPort: 8080
{{- end -}}
