{{- $fullName := include "snowstorm.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-snowstorm
  labels:
    app: snowstorm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowstorm
  template:
    metadata:
      labels:
        app: snowstorm
    spec:
      initContainers:
      - name: wait-for-elasticsearch
        image: public.ecr.aws/docker/library/busybox:1.36
        command: ['sh', '-c', 'until nc -z {{ $fullName }}-elasticsearch 9200; do echo "Waiting for Elasticsearch"; sleep 5; done;']
      containers:
      - name: snowstorm
        image: {{ .Values.snowstorm.image.repository }}:{{ .Values.snowstorm.image.tag }}
        imagePullPolicy: {{ .Values.snowstorm.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args: 
        - >
          java 
          -Xms2g -Xmx4g 
          --add-opens java.base/java.lang=ALL-UNNAMED 
          --add-opens=java.base/java.util=ALL-UNNAMED 
          -cp @/app/jib-classpath-file 
          org.snomed.snowstorm.SnowstormApplication 
          --elasticsearch.urls=http://{{ $fullName }}-elasticsearch:9200
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 15
          failureThreshold: 3
      volumes:
      - name: elastic-data
        emptyDir: {}
